CREATE TABLE babyaid_recipes_fourtosix (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    age_group TEXT NOT NULL,
    title TEXT NOT NULL UNIQUE,
    nutrients TEXT [],
    ingredients TEXT [], 
    directions TEXT [],
    recipe_url TEXT NOT NULL
);
CREATE TABLE babyaid_recipes_sixtoeight (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    age_group TEXT NOT NULL,
    title TEXT NOT NULL UNIQUE,
    nutrients TEXT [],
    ingredients TEXT [], 
    directions TEXT [],
    recipe_url TEXT NOT NULL
);
CREATE TABLE babyaid_recipes_eighttoten (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    age_group TEXT NOT NULL,
    title TEXT NOT NULL UNIQUE,
    nutrients TEXT [],
    ingredients TEXT [], 
    directions TEXT [],
    recipe_url TEXT NOT NULL
);
CREATE TABLE babyaid_recipes_tentotwelve (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    age_group TEXT NOT NULL,
    title TEXT NOT NULL UNIQUE,
    nutrients TEXT [],
    ingredients TEXT [], 
    directions TEXT [],
    recipe_url TEXT NOT NULL
);